#!/bin/bash

function showHelp() {
    # Display Help
    echo "Usage:"
    echo "  `basename $0` -a alpha"
    echo "  `basename $0` -h hex"
    echo
    echo "Options:"
    echo "  -a, --alpha     Print hex value from alpha (0-100)"
    echo "  -h, --help      Print alpha value from hex"
}

function fromAlpha() {
    if [ "$1" != "" ] && (( $1 <= 100 )) && (( $1 >= 0 )); then
        val=`/usr/bin/printf "%.0f" \`bc -l <<< "$1 * 2.55"\``
        val=0`echo "obase=16; ibase=10; $val" | bc`
        echo ${val:(-2)}
        exit 0
    fi
    echo "Please enter a valid alpha value between 0-100"
    exit 1
}

function fromHex() {
    val=`echo "obase=10; ibase=16; ${1^^}" | bc`
    val=`/usr/bin/printf "%.0f" \`bc -l <<< "$val / 2.55"\``
    if (( $val <= 100 )) && (( $val >= 0 )); then
        echo $val
        exit 0
    fi
    echo "Please enter a valid hex value between 00-FF"
    exit 1
}

while [[ $# -gt 0 ]]; do
    opt="$1";
    shift;
    case "$opt" in
        "-a" | "--alpha" )
           fromAlpha $1; shift;;
        "-h" | "--hex" )
           fromHex $1; shift;;
        "--help" )
           showHelp; shift;;
        *) echo >&2 "Invalid option: $opt. \"--help\" for help"; exit 1;;
   esac
done

