#!/bin/bash
# git update-index --skip-worktree filename
# git update-index --no-skip-worktree filename

# Sleep
export shouldSleep=true
# Time until i3lock activates
export lockTimer=900
# Time until sleep after lock
export sleepTimer=30
