#!/bin/bash

cmd='i3-msg'

if !( hash i3-msg 2>/dev/null ); then cmd='swaymsg'; fi

if [[ "$#" != 0 ]]; then
    current=$($cmd -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
    currentNum=$($cmd -t get_workspaces | jq '.[] | select(.focused==true).num')
    # Capitalize the first letter in each word
    name=$(echo $@ | sed -e "s/\b\(.\)/\u\1/g")
    if [[ ! $@ =~ [0-9] ]]; then
        # No numbers
        index=1
        changed=false
        for i in $($cmd -t get_workspaces | jq '.[].num' | sort -n); do
            # Check for smallest avilable number
            if [[ ! "$index" == "$i" ]]; then
                # Checks if the selected number is smaller than the current wp number
                if [ $index -lt $currentNum ]; then
                    name="${index} ${name}"
                    changed=true
                    break
                fi
            fi
            ((index++))
        done
        if [ $changed == false ]; then
            name="${currentNum} ${name}"
        fi
    fi
    $cmd rename workspace \"$current\" to \"${name}\" >/dev/null
fi
