#!/bin/bash
read -p "Input email: " email
read -p "Key location  ($HOME/.ssh/id_rsa): " name
if [[ "$name" == "" ]]; then name="id_rsa"; fi
ssh-keygen -t rsa -b 4096 -C "$email" -f "$HOME/.ssh/$name"
ssh-add "$HOME/.ssh/$name"
