fork = true
idle = true
mouse-cursor-icon = "arrow"
no-multigrid = false
tabs = false
theme = "auto"
vsync = true

[font]
size = 13
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[[font.normal]]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[font.bold]]
family = "FiraCode Nerd Font Mono"
style = "Bold"
