#! /bin/sh
~/.config/bspwm/scripts/init.sh &

~/.config/bspwm/scripts/mainLockScript.sh &

# Set the wallpaper
pgrep -x xrandr-watcher >/dev/null || xrandr-watcher ~/.config/bspwm/scripts/xrandr-change.sh All &

autorandr -c --skip-options gamma,brightness

~/.config/bspwm/scripts/xrandr-change.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 12
bspc config border_radius 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pgrep -x sxhkd >/dev/null || sxhkd &
