#!/bin/bash

export common=(
    "wmname"
    "ibus"
    "polkit-gnome"
    "gnome-keyring"
    "xdg-desktop-portal"
    "kanshi"
    "gammastep"
    "wdisplays"
    "kitty"
    "qt5ct"
    "qt6ct-kde"
    "satty"
    "geocode-glib"
    "brightnessctl"
    "playerctl"
    "lxappearance"
    "wl-clipboard"
    "wf-recorder"
    "grim"
    "grimshot"
    "slurp"
    "wlogout"
    "swappy"
    "swayidle"
    "udiskie"
    "hyprlock"
    "poweralertd"
    "wayland-logout"
)

export arch=(
    "pacdep"
    "ttf-material-icons-git"
    "avizo"
    "swaytools"
    "wallutils"
    "otf-font-awesome"
    "ttf-font-awesome"
    "appimagelauncher"
    "libappimage"
    "xembed-sni-proxy-git"
)

export fedora=(
    "redhat-lsb"
    "dbus-python-devel"
    "python3-dbus"
    "xdg-desktop-portal-wlr"
    "geoclue2"
    "geoclue2-libs"
    "gammastep-indicator"
    "bluez"
    "bluez-tools"
    "qt5-qtconfiguration"
    "rofi-wayland"
    # TODO: ttf-weather-icons

    # Wallpapers
    "verne-backgrounds-extras-gnome"
    "verne-backgrounds-gnome"
    "schroedinger-cat-backgrounds-extras-gnome"
    "schroedinger-cat-backgrounds-gnome"
    "deepin-wallpapers"
    "adapta-backgrounds"
    "cosmic-wallpapers"
    "gnome-backgrounds"
    "desktop-backgrounds-compat"
    "desktop-backgrounds-gnome"
    "f37-backgrounds-base"
    "f37-backgrounds-gnome"
    "f38-backgrounds-base"
    "f38-backgrounds-gnome"
    "f39-backgrounds-base"
    "f39-backgrounds-gnome"
    "f40-backgrounds-base"
    "f40-backgrounds-gnome"
    "f41-backgrounds-base"
    "f41-backgrounds-gnome"
    "f42-backgrounds-base"
    "f42-backgrounds-gnome"
    "fedora-workstation-backgrounds"
    "gnome-shell-extension-background-logo"
    "schroedinger-cat-backgrounds-animated"
    "schroedinger-cat-backgrounds-base"
    "schroedinger-cat-backgrounds-extras-base"
    "verne-backgrounds-extras-single"
    "verne-backgrounds-single"

    # avizo
    # swaytools
    # wallutils
)

export lure=(
    "autotiling-git"
    # "font-awesome" # Due to issues in CSGO console font rendering. A fontconfig should probably fix?
    "rofi-emoji"
    "sway-audio-idle-inhibit-git"
    "swayfloatingswitcher-git"
    "swayfx-git"
    "swaync-git"
    "swaylock-effects-erikreider-git"
    "swayosd-git"
    "swayscratchpad-git"
    "swaysettings-git"
    "waybar-git"
)
